---

- name: Ensure the needed dirs are present and Jenkins is privileged
  file:
    path: "{{ item }}"
    owner: "{{ OWNER }}"
    group: "{{ GROUP }}"
    mode: 0777
    state: directory
  with_items:
    - "{{ backup_script_dir }}"
    - "{{ backup_dir }}"

- name: Copy script sh files
  template:
    src: "templates/scripts/{{ item }}"
    dest: "{{ backup_script_dir }}jenkins-config-backup.sh"
    owner: "{{ OWNER }}"
    group: "{{ GROUP }}"
    mode: 0750
  with_items:
    - "jenkins-config-backup.sh.j2"



#- name : setup cron backup
#  cron:
#    name: "jenkins-backup"
#    special_time: hourly
#    job: "{{ backup_script_dir }}/jenkins-config-backup.sh > /dev/null 2>&1"
#    user: "admin"
#    cron_file: "jenkins_backup"
